#!/usr/bin/env python3
import os
import re
import urllib.request
import urllib.error
import json
import yaml
from pathlib import Path

MODEL_NAME = "nvidia/nemotron-3-super-120b-a12b:free"

def call_openrouter(prompt):
    """Call OpenRouter API with the free Nemotron model"""
    api_key = os.environ.get("OPENROUTER_API_KEY")
    if not api_key:
        raise ValueError("OPENROUTER_API_KEY environment variable is not set")
    
    url = "https://openrouter.ai/api/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        "HTTP-Referer": "https://wsslab.org", # Required by OpenRouter
        "X-Title": "WSSL News Issue Script"
    }
    
    data = {
        "model": MODEL_NAME,
        "messages": [
            {"role": "user", "content": prompt}
        ],
        "response_format": {"type": "json_object"}
    }
    
    req = urllib.request.Request(
        url,
        data=json.dumps(data).encode("utf-8"),
        headers=headers,
        method="POST"
    )
    
    try:
        with urllib.request.urlopen(req) as response:
            res_data = json.loads(response.read().decode("utf-8"))
            if "choices" not in res_data or not res_data["choices"]:
                raise ValueError(f"Unexpected response from OpenRouter: {res_data}")
            return res_data["choices"][0]["message"]["content"]
    except urllib.error.HTTPError as e:
        error_body = e.read().decode('utf-8') if e else ""
        print(f"HTTP Error: {e.code} - {e.reason}\nBody: {error_body}")
        raise e

def convert_to_news_json(raw_text):
    """Parse raw news text and convert to a JSON news item via OpenRouter"""
    prompt = f"""
    You are an assistant formatting news items.
    Convert the following news text into a single JSON object containing:
    - "date": formatted as "MM/YYYY" (e.g. 03/2026 or 12/2025)
    - "content": the text description.
      CRITICAL instructions:
      1. Remove any leading date prefixes (like "03 - 2026:" or "02 - 2026:") from this text so it starts directly with the news description.
      2. Since this news is for the official lab website, convert any first-person pronouns (like "I", "my", "me") into:
         - "Prof. Nguyen" (or "Prof. Phuc Nguyen") if the news refers specifically to the advisor's individual achievements/actions (e.g., serving as a chair, receiving a personal award, giving a talk).
         - "We", "our", or "us" if the news refers to the lab team as a whole or joint team achievements.
    - "highlights": (optional) list of objects containing 'content' (link text) and 'url' (hyperlink) if there are links/highlights mentioned.
    
    Return ONLY valid JSON.
    
    News text:
    {raw_text}
    """
    
    print("Calling OpenRouter to parse news...")
    response_text = call_openrouter(prompt)
    try:
        return json.loads(response_text)
    except json.JSONDecodeError as e:
        print(f"Failed to parse JSON: {response_text}")
        raise e

def merge_news(new_item, news_file_path):
    """Prepend the new news item to news.yml, avoiding exact duplicates"""
    if not new_item or not new_item.get("content"):
        raise ValueError("Invalid news item generated by LLM")
        
    print(f"Loading existing news from {news_file_path}")
    existing_news = []
    if news_file_path.exists():
        with open(news_file_path, 'r', encoding='utf-8') as f:
            existing_news = yaml.safe_load(f) or []
            
    # Simple deduplication checks
    def normalize(text):
        return re.sub(r'[^a-z0-9]', '', text.lower())
        
    new_norm = normalize(new_item.get("content", ""))
    for item in existing_news:
        if normalize(item.get("content", "")) == new_norm:
            print("🛑 News item already exists. Skipping.")
            return False
            
    # Prepend new item
    existing_news.insert(0, new_item)
    
    # Sort news reverse-chronologically
    def get_date_key(item):
        date_str = str(item.get("date", ""))
        match = re.match(r'(\d{1,2})/(\d{4})', date_str)
        if match:
            return (int(match.group(2)), int(match.group(1)))
        match_other = re.match(r'(\d{1,2})/(\d{1,2})/(\d{2,4})', date_str)
        if match_other:
            year_val = match_other.group(3)
            year = int(year_val) + (2000 if len(year_val) == 2 else 0)
            return (year, int(match_other.group(2)), int(match_other.group(1)))
        return (0, 0)

    existing_news.sort(key=get_date_key, reverse=True)

    with open(news_file_path, 'w', encoding='utf-8') as f:
        yaml.dump(existing_news, f, allow_unicode=True, sort_keys=False, default_flow_style=False)
    print(f"✅ Successfully added and sorted new news: {new_item.get('content')[:60]}...")
    return True

def main():
    project_root = Path(__file__).parent.parent
    news_file = project_root / '_data' / 'news.yml'
    
    issue_body = os.environ.get("ISSUE_BODY")
    if not issue_body:
        raise ValueError("ISSUE_BODY environment variable is empty or not set.")
        
    issue_body = re.sub(r'<!--.*?-->', '', issue_body, flags=re.DOTALL).strip()
    
    news_item = convert_to_news_json(issue_body)
    merge_news(news_item, news_file)

if __name__ == '__main__':
    main()
